application:
  name: 'Task manager'
server:
  port: 8088
jwt:
  issuer: 'danfromomsk@gmail.com'
  signingKey: '251853hero'
  aTokenDuration: 30
spring:
  profiles:
    active: console-and-file-logging
  datasource:
    tasks:
      jdbcUrl: jdbc:postgresql://localhost:5432/eisetasks
      username: daniil
      password: 251853Hero
      driver-class-name: org.postgresql.Driver
parameters:
  min-page-size: 10
  max-page-size: 50
utils:
  date-pattern: yyyy-MM-dd'T'HH:mm:ssxxx
logging:
  config: "classpath:logback-spring.xml"
  file:
    max-size: 512K
  path: /var/logs/mytasks
  level:
    root: INFO
    org.springframework.web: INFO
    it.sevenbits.courses.example.spring.security.web.security.JsonWebTokenService: DEBUG