server:
  port: 8080
jwt:
  issuer: 'danfromomsk@gmail.com'
  signingKey: '251853hero'
  aTokenDuration: 30
spring:
  datasource:
    tasks:
      jdbcUrl: jdbc:postgresql://localhost:5432/eisetasks
      username: daniil
      password: 251853Hero
      driver-class-name: org.postgresql.Driver
utils:
  date-pattern: yyyy-MM-dd'T'HH:mm:ssxxx
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    it.sevenbits.courses.example.spring.security.web.security.JsonWebTokenService: DEBUG